### ISSUE TITLE
Add support for time zone aliases

### ISSUE THREAD

**Issue by jcfranco** [jcfranco/timezone-groups#1]
According to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, time zones can be referenced by an alias (link time zone). The grouping logic should provide a way to define aliases, so they can be included in `tzs` (both link and canonical time zones), but ignored when generating `labelTzIndices` (canonical only). 

For example, when running `Intl.supportedValuesOf("timeZone")`, Chrome's result includes `Asia/Katmandu`, whereas Firefox's includes `Asia/Kathmandu`.

**Comment by richiecarmichael** [comment]
More importantly the ECMA specification states that a [time zone identifier](https://tc39.es/ecma262/#sec-time-zone-identifiers) as used in various `Intl` methods can be one of the following:
1. A _primary time zone identifier_ (same as a **canonical** IANA time zone),
2. A _non-primary time zone identifier_ (same as a **link** IANA time zone), _or_
3. An _offset time zone_ (e.g. `+hh:mm`) (see [here](https://tc39.es/ecma262/#prod-UTCOffset))

Reading (3) is new to me. This is good to know but hopefully never used.

The following statement also confirms that both canonical and link IANA time zones are acceptable inputs in ECMA script.
> A conforming implementation must recognize "UTC" and all **Zone** and **Link** names from the IANA Time Zone Database...
_(from [here](https://tc39.es/ecma402/#sec-tolocaltime))_

In the cases where a user specifies a link IANA time zone, should it be mapped to zoned/canonical time zone?

**Comment by jcfranco** [comment]
@richiecarmichael Thanks for sharing the spec! I'll update the description to use proper terminology.

I was thinking groups would need to include both canonical and link time zones, but only use canonical for labeling. 

> In the cases where a user specifies a link IANA time zone, should it be mapped to zoned/canonical time zone?

I'm not sure I follow. Users don't specify time zones when using `timezone-groups`.

**Comment by richiecarmichael** [comment]
I mean, if a user specifies a linked time zone, we automatically return or show the corresponding canonical/zoned time zone?
```ts
// A user specifies a linked time zone
const view = new MapView({ timeZone: "Antarctica/South_Pole" });

// Perhaps always write the canonical/zoned equivalent
console.log(view.write({})); // { timeZone: "Pacific/Auckland" }
```
Similarly if a user set the value to "Antarctica/South_Pole"...
```html
<calcite-input-time-zone mode="name" value="Antarctica/South_Pole"></calcite-input-time-zone>
```
...should we show Auckland in the UI?
![image](https://github.com/jcfranco/timezone-groups/assets/2531121/2885f9c8-3655-4d23-9b3c-f52529cf97b7)

btw. I don't know the answer to these. 😄

**Comment by jcfranco** [comment]
I think this discussion is better suited for https://github.com/Esri/calcite-design-system/, but to answer your question, I _think_ the component should map the linked time zone to a canonical one.

BTW, I also don't know the answer to these. 😅

**Comment by jcfranco** [comment]
Fixed by https://github.com/jcfranco/timezone-groups/commit/23bf3cb32d379bf7763ef6063369bf037545f99d, which added a `normalize` utility function to return aliases for deprecated time zones (handled by [countries-and-timezones](https://www.npmjs.com/package/countries-and-timezones)).
