### ISSUE TITLE
Feature: expose timezone-groups/dist/groupByOffset/strategy/native/index.mjs

### ISSUE THREAD

**Issue by maxpatiiuk** [jcfranco/timezone-groups#3]
In the following place Calcite is importing the `timezone-groups/dist/groupByOffset/strategy/native/index.mjs` file from this package:

https://github.com/Esri/calcite-design-system/blob/00a78da2bf8059e756ba1401ffa506ec2573a942/packages/calcite-components/src/components/input-time-zone/utils.ts#L127

However, that file is not specified in the export mappings in the current package:

https://github.com/jcfranco/timezone-groups/blob/main/package.json#L13

While this works at the moment since Calcite is using an older TypeScript moduleResolution option that does not respect export mappings, this is going to cause an error once Calcite's TypeScript settings are updated.

@jcfranco could you update the export mappings for this package, publish a new version and consume it in Calcite?

**Comment by jcfranco** [comment]
Fixed by d0b0f3f05250079d896e1cde9105c7f7239c3ff5. 

I have some additional updates coming along, so I'll publish a new version right after. Thanks for submitting!
